sudo: required
services:
  - docker

brfore_install:
  - docker build -t udhsingh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true udhsingh/xt_rick_n_morty npm run test -- --coverage

after_success:
  - docker build -t udhsingh/multi-client ./client
  - docker build -t udhsingh/multi-nginx ./nginx
  - docker build -t udhsingh/multi-server ./server
  - docker build -t udhsingh/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to docker hub
  - docker push udhsingh/multi-client
  - docker push udhsingh/multi-nginx
  - docker push udhsingh/multi-server
  - docker push udhsingh/multi-worker